/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4206)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [TransactionsDB]    Script Date: 29/04/2018 23:31:40 ******/
CREATE DATABASE [TransactionsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TransactionsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.UMRMSSQL20170912\MSSQL\DATA\TransactionsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TransactionsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.UMRMSSQL20170912\MSSQL\DATA\TransactionsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TransactionsDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TransactionsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TransactionsDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TransactionsDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TransactionsDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TransactionsDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TransactionsDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TransactionsDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TransactionsDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TransactionsDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TransactionsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TransactionsDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TransactionsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TransactionsDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TransactionsDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TransactionsDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TransactionsDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TransactionsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TransactionsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TransactionsDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TransactionsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TransactionsDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TransactionsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TransactionsDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TransactionsDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TransactionsDB] SET  MULTI_USER 
GO

ALTER DATABASE [TransactionsDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TransactionsDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TransactionsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TransactionsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TransactionsDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TransactionsDB] SET QUERY_STORE = OFF
GO

USE [TransactionsDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TransactionsDB] SET  READ_WRITE 
GO


