//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {

        }
        public Transaction(string currency, string amount)
        {
            this.Currency = currency;
            this.InvalidAmount = amount;
        }
        public Transaction(string currency, decimal amount )
        {
            this.Currency = currency;
            this.Amount = amount;
            this.InvalidAmount = "";
        }
        public int Id { get; set; }
        public string Currency { get; set; }    
        public string InvalidAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
